#!/bin/bash

dir="$(cd "$(dirname "$0")" && pwd -P)"
olddir=$dir/dotfiles_old

function install {
    echo "Update submodules"
    git submodule update

    echo "Moving any existing dotfiles from ~ to $olddir"
    mv ~/.$1 $olddir

    echo "Creating symlink to $1 in home directory."
    ln -s $dir/$1 ~/.$1
}

install $1
