#!/bin/bash

dir="$(cd "$(dirname "$0")" && pwd -P)"
olddir=$dir/dotfiles_old

function install {
    echo "Update submodules"
    git submodule update --init --recursive

    for module in "$@"
    do
        echo "Moving any existing dotfiles from ~ to $olddir"
        mv ~/.$module $olddir

        echo "Creating symlink to $module in home directory."
        ln -s $dir/$module ~/.$module
    done

}

install $@
